// Generated by gencpp from file t4ac_msgs/Vehicle.msg
// DO NOT EDIT!


#ifndef T4AC_MSGS_MESSAGE_VEHICLE_H
#define T4AC_MSGS_MESSAGE_VEHICLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <t4ac_msgs/Location.h>
#include <t4ac_msgs/Waypoint.h>

namespace t4ac_msgs
{
template <class ContainerAllocator>
struct Vehicle_
{
  typedef Vehicle_<ContainerAllocator> Type;

  Vehicle_()
    : vehicle_id(0)
    , enter_time(0)
    , current_waypoint()
    , waypoints()  {
    }
  Vehicle_(const ContainerAllocator& _alloc)
    : vehicle_id(0)
    , enter_time(0)
    , current_waypoint(_alloc)
    , waypoints(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _vehicle_id_type;
  _vehicle_id_type vehicle_id;

   typedef int32_t _enter_time_type;
  _enter_time_type enter_time;

   typedef  ::t4ac_msgs::Location_<ContainerAllocator>  _current_waypoint_type;
  _current_waypoint_type current_waypoint;

   typedef std::vector< ::t4ac_msgs::Waypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::t4ac_msgs::Waypoint_<ContainerAllocator> >> _waypoints_type;
  _waypoints_type waypoints;





  typedef boost::shared_ptr< ::t4ac_msgs::Vehicle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::t4ac_msgs::Vehicle_<ContainerAllocator> const> ConstPtr;

}; // struct Vehicle_

typedef ::t4ac_msgs::Vehicle_<std::allocator<void> > Vehicle;

typedef boost::shared_ptr< ::t4ac_msgs::Vehicle > VehiclePtr;
typedef boost::shared_ptr< ::t4ac_msgs::Vehicle const> VehicleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::t4ac_msgs::Vehicle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::t4ac_msgs::Vehicle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::t4ac_msgs::Vehicle_<ContainerAllocator1> & lhs, const ::t4ac_msgs::Vehicle_<ContainerAllocator2> & rhs)
{
  return lhs.vehicle_id == rhs.vehicle_id &&
    lhs.enter_time == rhs.enter_time &&
    lhs.current_waypoint == rhs.current_waypoint &&
    lhs.waypoints == rhs.waypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::t4ac_msgs::Vehicle_<ContainerAllocator1> & lhs, const ::t4ac_msgs::Vehicle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace t4ac_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::t4ac_msgs::Vehicle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::t4ac_msgs::Vehicle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t4ac_msgs::Vehicle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::t4ac_msgs::Vehicle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t4ac_msgs::Vehicle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::t4ac_msgs::Vehicle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::t4ac_msgs::Vehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bb831235a6a75a24b4ee343d565fc99";
  }

  static const char* value(const ::t4ac_msgs::Vehicle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bb831235a6a75a2ULL;
  static const uint64_t static_value2 = 0x4b4ee343d565fc99ULL;
};

template<class ContainerAllocator>
struct DataType< ::t4ac_msgs::Vehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "t4ac_msgs/Vehicle";
  }

  static const char* value(const ::t4ac_msgs::Vehicle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::t4ac_msgs::Vehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Vehicle\n"
"# project name t4ac_global_planner_ros\n"
"\n"
"int32 vehicle_id\n"
"int32 enter_time\n"
"# Odometry start_point\n"
"# PoseStamped end_point\n"
"Location current_waypoint\n"
"Waypoint[] waypoints\n"
"\n"
"================================================================================\n"
"MSG: t4ac_msgs/Location\n"
"# T4ac Project \n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: t4ac_msgs/Waypoint\n"
"# T4ac Project \n"
"\n"
"Header header\n"
"int32 id\n"
"Transform transform\n"
"int32 road_id\n"
"int32 lane_id\n"
"int32 junction\n"
"float64 s\n"
"float64 lane_width\n"
"string lane_change\n"
"string lane_type\n"
"string right_lane_marking\n"
"string left_lane_marking\n"
"int32 vmax\n"
"string vunit\n"
"int32 nLanes\n"
"int32 lanePosition\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: t4ac_msgs/Transform\n"
"# T4ac Project\n"
"\n"
"Location location\n"
"Rotation rotation\n"
"================================================================================\n"
"MSG: t4ac_msgs/Rotation\n"
"# T4ac Project \n"
"\n"
"float64 pitch\n"
"float64 yaw\n"
"float64 roll\n"
;
  }

  static const char* value(const ::t4ac_msgs::Vehicle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::t4ac_msgs::Vehicle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vehicle_id);
      stream.next(m.enter_time);
      stream.next(m.current_waypoint);
      stream.next(m.waypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vehicle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::t4ac_msgs::Vehicle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::t4ac_msgs::Vehicle_<ContainerAllocator>& v)
  {
    s << indent << "vehicle_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vehicle_id);
    s << indent << "enter_time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.enter_time);
    s << indent << "current_waypoint: ";
    s << std::endl;
    Printer< ::t4ac_msgs::Location_<ContainerAllocator> >::stream(s, indent + "  ", v.current_waypoint);
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::t4ac_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // T4AC_MSGS_MESSAGE_VEHICLE_H
