# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from t4ac_msgs/CarState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class CarState(genpy.Message):
  _md5sum = "6104b11829402233723a0180a9d22973"
  _type = "t4ac_msgs/CarState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# Created by J Felipe Arango - UAH - Robesafe

Header header
bool manual_mode
bool ready_mode
bool automatic_mode
bool actuated_brake
bool actuated_wheel
bool reverse
bool forward
bool parked

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','manual_mode','ready_mode','automatic_mode','actuated_brake','actuated_wheel','reverse','forward','parked']
  _slot_types = ['std_msgs/Header','bool','bool','bool','bool','bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,manual_mode,ready_mode,automatic_mode,actuated_brake,actuated_wheel,reverse,forward,parked

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CarState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.manual_mode is None:
        self.manual_mode = False
      if self.ready_mode is None:
        self.ready_mode = False
      if self.automatic_mode is None:
        self.automatic_mode = False
      if self.actuated_brake is None:
        self.actuated_brake = False
      if self.actuated_wheel is None:
        self.actuated_wheel = False
      if self.reverse is None:
        self.reverse = False
      if self.forward is None:
        self.forward = False
      if self.parked is None:
        self.parked = False
    else:
      self.header = std_msgs.msg.Header()
      self.manual_mode = False
      self.ready_mode = False
      self.automatic_mode = False
      self.actuated_brake = False
      self.actuated_wheel = False
      self.reverse = False
      self.forward = False
      self.parked = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8B().pack(_x.manual_mode, _x.ready_mode, _x.automatic_mode, _x.actuated_brake, _x.actuated_wheel, _x.reverse, _x.forward, _x.parked))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.manual_mode, _x.ready_mode, _x.automatic_mode, _x.actuated_brake, _x.actuated_wheel, _x.reverse, _x.forward, _x.parked,) = _get_struct_8B().unpack(str[start:end])
      self.manual_mode = bool(self.manual_mode)
      self.ready_mode = bool(self.ready_mode)
      self.automatic_mode = bool(self.automatic_mode)
      self.actuated_brake = bool(self.actuated_brake)
      self.actuated_wheel = bool(self.actuated_wheel)
      self.reverse = bool(self.reverse)
      self.forward = bool(self.forward)
      self.parked = bool(self.parked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8B().pack(_x.manual_mode, _x.ready_mode, _x.automatic_mode, _x.actuated_brake, _x.actuated_wheel, _x.reverse, _x.forward, _x.parked))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.manual_mode, _x.ready_mode, _x.automatic_mode, _x.actuated_brake, _x.actuated_wheel, _x.reverse, _x.forward, _x.parked,) = _get_struct_8B().unpack(str[start:end])
      self.manual_mode = bool(self.manual_mode)
      self.ready_mode = bool(self.ready_mode)
      self.automatic_mode = bool(self.automatic_mode)
      self.actuated_brake = bool(self.actuated_brake)
      self.actuated_wheel = bool(self.actuated_wheel)
      self.reverse = bool(self.reverse)
      self.forward = bool(self.forward)
      self.parked = bool(self.parked)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_8B = None
def _get_struct_8B():
    global _struct_8B
    if _struct_8B is None:
        _struct_8B = struct.Struct("<8B")
    return _struct_8B
